---

spring:
  config:
    activate:
      on-profile: local
    datasource:
      jdbc-url: jdbc:mariadb://localhost:7701/post-db
      username: post-user
      password: post-pwd-01
      driver-class-name: org.mariadb.jdbc.Driver
    datasource:
      jdbc-url: jdbc:mariadb://localhost:7702/user-db
      username: client-user
      password: user-pwd-01
      driver-class-name: org.mariadb.jdbc.Driver

datasource:
  post:
    jdbcUrl: jdbc:mariadb://localhost:7701/post-db
    username: post-user
    password: post-pwd-01
    driver-class-name: org.mariadb.jdbc.Driver
    liquibase:
      change-log: classpath:/db/changelog/db.post.changelog-master.yaml
  user:
    jdbcUrl: jdbc:mariadb://localhost:7702/user-db
    username: client-user
    password: user-pwd-01
    driver-class-name: org.mariadb.jdbc.Driver
    liquibase:
      change-log: classpath:/db/changelog/db.user.changelog-master.yaml
