---

spring:
  config:
    activate:
      on-profile: local
datasource:
  lessons:
    jdbc-url: jdbc:mariadb://localhost:7701/post-db
    username: post-user
    password: post-pwd-01
    liquibase:
      change-log: classpath:/db/changelog/db.post.changelog-master.yaml
  notations:
    jdbc-url: jdbc:mariadb://localhost:7702/user-db
    username: client-user
    password: user-pwd-01
    liquibase:
      change-log: classpath:/db/changelog/db.user.changelog-master.yaml
