server:
  port: 7100

---

spring:
  config:
    activate:
      on-profile: local
  r2dbc: 
    url: r2dbc:mariadb://localhost:7701/socialmedia-db
    username: socialmedia-user
    password: socialmedia-pwd-01
